### ISSUE TITLE
No isolated lots generating (castle, radio tower, tents, etc)

### ISSUE THREAD

**Issue by keenerb** [echurchill/CityWorld#13]
In naturecontext, 

if (state != HeightState.BUILDING && 
			generator.shapeProvider.isIsolatedConstructAt(platmap.originX + x, platmap.originZ + z, oddsOfIsolatedConstructs / 2))

is never true, microscaleat seems to generate only numbers between 0.5 and 1; oddsofIsolatedConstructs is .125, so it is impossible for one to be generated.

**Comment by keenerb** [comment]
I've been tinkering with the 1.8 spigot builds and don't see any isolated plots.

**Comment by echurchill** [comment]
Interesting, I will take a look at it

**Comment by echurchill** [comment]
I see them from time to time, I think this is fixed... again
