### ISSUE TITLE
License/permissions question...

### ISSUE THREAD

**Issue by keenerb** [echurchill/CityWorld#19]
I don't see a license attached to this project, and I'd like to export some of the ruined buildings that it generates as schematic files.  Your bukkit page has GPL v3 listed, but I'd like to avoid any grey area.

Essentially I'd be using worldedit to grab chunks of a generated world and export into schematic format to use with other worldgen utilities.  The end result will probably be featured in a fairly high-visibility MinecraftForge modpack.  Some of the buildings, houses, radio towers, etc. would be specifically targetted.

Kind of an odd request but I like to be fastidious about permissions in circumstances like this, and would only push forward with the plan if you have no objections.

Credit for the structures would, of course, be given to your worldgen utility.

**Comment by echurchill** [comment]
Ok with me. Love to hear more when the effort gets public
