### ISSUE TITLE
Radio towers not generating antenna

### ISSUE THREAD

**Issue by keenerb** [echurchill/CityWorld#20]
Not sure why yet.  No radio tower has had an antenna at all in my decayed nature world.

*edit*
Ah, it's intentional? RadioTowerLot.java, line 112, it skips antenna/ladder placement if it's decayed buildings.  I think that shouldn't be the case...

**Comment by echurchill** [comment]
I think I was just in a rush and did that as a shortcut. I will take a look at it

**Comment by echurchill** [comment]
should work better now... actually it has been working for while... I just forgot to mention and close this
