### ISSUE TITLE
Feature request:  "Only generate city" radius option

### ISSUE THREAD

**Issue by keenerb** [echurchill/CityWorld#21]
Would it be possible to have a radius range where ONLY city plots are generated?

I kind of doubt it based on how the mountain/seas intersperse in the generation algorithm, but it'd be nice to have a largish contiguous central city area and then mountains/lakes/seas generating afterwards.

**Comment by echurchill** [comment]
Well... you can do that but first you need to find a central city you like and get it's coordinates and use them with "CenterPointOfChunkRadiusX", "...Z" (these are in absolute block coordinates), "RoadChunkRadius" & "CityChunkRadius" (these are in numbers of chunks). Nature will generate outside of them. This code has been checked in a for a while.

Oddly enough I just got a request to allow inversion of the logic... a circle of Nature surrounded by normal road/city/nature generation. In fact I check in that code a few hours ago. :-)

**Comment by keenerb** [comment]
Hm I don't think those chunk radius etc. optiosn did what I was looking for, but I haven't used your latest code until now.  I'll double-check and see.  Thanks.

**Comment by echurchill** [comment]
Here is a picture that helps visualize it
http://dev.bukkit.org/bukkit-plugins/cityworld/images/44-radius/

**Comment by keenerb** [comment]
OK, so what I"m talking about is EVERYTHING within that radius being city; no mountains, no forest, no  oceans, etc.

**Comment by echurchill** [comment]
The yellow line is the RoadChunkRadius, the red is CityChunkRadius. In addition you can also control additional constructs being generated.

**Comment by echurchill** [comment]
For any given seed, finding that really flat area is programmatically difficult. That is why I suggest to folks to create the world with something like Multiverse & CityWorld and go look for the city they want. Write down the coordinate and figure out how much radius they need. Shut down the server. Change the CityWorld.yml file to reflect that world's new generation center and radius they want. Delete the region data in <worldname>/region but leave everything else alone. Start server/client and using Multiverse (or whatever world manager you use) go back to your world. CityWorld will regenerate but with the limits you put into CityWorld.yml.
