### ISSUE TITLE
port to sponge?

### ISSUE THREAD

**Issue by nightstalker6669** [echurchill/CityWorld#22]
just wanted to know if you were going to be porting this plugin to sponge? I think it would be pretty cool to see on a spongeforge server.

**Comment by echurchill** [comment]
I have been keeping an eye on Sponge, right now it is about 5 releases back behind Minecraft. Say what you will about the Spigot folks, they do their damndest to keep up with Minecraft. When I have played with Sponge it seems to generate worlds quite bit slower than vanilla Minecraft (without mods or plugins). Have you noticed anything like that on your end?  Mind you it could be just random (it is amazing what the "wrong" seed will do the generator). 

Anyway, I am not saying no to Sponge right now... with that said, based on things said at E3, I wonder if the Mojang/Minecraft folks may finally release an official API in the next 12 months. That would be something I would have to port to. Too soon to tell I guess.

**Comment by nightstalker6669** [comment]
Yeah sponge can only move as fast as forge does when it comes to updating. I run a fully modded server and haven't really had any problems with world gen. I just started moving on to sponge and I'm really happy with the results over bukkit/spigot. Also the community is amazing and very helpful. And as far as an actual mine craft api, I'd be surprised. They've been saying this for atleast a year if not longer. But hey you never know. Well I hope you give it a good thought cause I think the sponge api will eventually far surpass anything bukkit or spigot can do.

**Comment by Lucavon** [comment]
If I find the time, I might try to do it!
