### ISSUE TITLE
Feature Request:  Burning buildings

### ISSUE THREAD

**Issue by keenerb** [echurchill/CityWorld#26]
In the apocalypse/desert world options, it would be interesting to have buildings generated that are engulfed in flames, occasionally.  With fire management plugins it could be a pretty impressive sight.

**Comment by echurchill** [comment]
Agreed... mind you if you don't have those plugins then the world might be in trouble. Which plugins do you use?

**Comment by echurchill** [comment]
Ok... I added a bit in v4.05. didn't want to over do it. :-)
