### ISSUE TITLE
No seagrass under the bridge

### ISSUE THREAD

**Issue by jyhsu2000** [echurchill/CityWorld#32]
As the picture shows,
there is no seagrass in the water under the bridge and the oil platform.
![2019-01-04_16 49 27](https://user-images.githubusercontent.com/6276648/50680079-51a1fd00-1041-11e9-8b1f-eeb461ba52da.png)

![2019-01-13_20 32 44](https://user-images.githubusercontent.com/6276648/51085351-8e24d580-1772-11e9-8ae2-abe776089ec0.png)

**Comment by SlimeDog** [comment]
Is that because there is no sunlight penetration?

**Comment by echurchill** [comment]
No, just me being lazy :-)

I will try to get to that this weekend.

**Comment by echurchill** [comment]
It is fixed but some folks contributed to CityWorld but the integration didn't go well. I will get v4.05 fixed up and posted when I get back from a trip. eta 2/3

**Comment by echurchill** [comment]
About to post v4.05 with the fixes for this
