### ISSUE TITLE
Anomalous object

### ISSUE THREAD

**Issue by SlimeDog** [echurchill/CityWorld#34]
Spigot 1.13.2
CityWorld 4.04

I discovered this at Y={232,238}. Any ideas?

![screen shot 2019-01-19 at 11 21 12 pm](https://user-images.githubusercontent.com/17748923/51436386-2a524f00-1c41-11e9-81ce-05bb013fdfc6.png)

**Comment by DartPower** [comment]
This is a UFO

**Comment by SlimeDog** [comment]
Well, of course it is. :)
