### ISSUE TITLE
Setting IncludeAirborneStructures to false still allows hot air balloons to generate in farm plots

### ISSUE THREAD

**Issue by kosakriszi** [echurchill/CityWorld#35]
I would love to have farm plots in my world without some of them having hot air balloons in them, would it be possible to the Airborne structures setting prevent this from happening?

Thanks!

**Comment by echurchill** [comment]
oops, I will fix that this weekend. Thanks for the report.

**Comment by echurchill** [comment]
Found the problem, it will be fixed in v4.05. Which should be released this weekend

**Comment by echurchill** [comment]
Done, or will be once I post the update

**Comment by echurchill** [comment]
Wow you have been busy... it seems that you want to contribute. :-)

I just noticed the pull requests. Wow that is a lot of code to sift through. 

I can't integrate the changes right this second, about to go out of town. I love the loot work, I really dislike the code I am currently using. Would you mind integrating v4.05 and resubmitting the pull request this week. I will look it over when I get back next weekend and include it in v4.06.

I really appreciate the effort, on a quick glance it looks like good stuff!

**Comment by echurchill** [comment]
Ok about to post 4.05 with the fixes
