### ISSUE TITLE
[Question] Can CityWorld be combined with the vanilla generator?

### ISSUE THREAD

**Issue by ghost** [echurchill/CityWorld#46]
I'm thinking about making CityWorld a rare, but locatable place within my main world. The idea is I want to make it mostly vanilla terrain, but with CityWorld cities appearing every once in a while.

**Comment by echurchill** [comment]
I really wish that was possible but Bukkit/Spigot doesn't seem to support that. It was one of the reasons that I gave cityworld configuration options to prevent cities from showing up the world as much. Alas that simply means the "natural" world generator of CityWorld (which I never was satisfied with) fills in where the city wasn't generator.
